### ISSUE TITLE
decrypt not working ,return a blank string.

### ISSUE THREAD

**Issue by cnritng** [ifduyue/xxtea#12]
decrypt a base64 encode data fail,
Original Base64 Data:
'AwCAAAAAAAD/////AIAAALAFAC120z+he5wg0Hyu5WKtwk75YUr6b/0DasM3Ut8cMkFlZ5YmvcLqUBKNEwRhcEJV0Zc='

data after Base64 Decode:
'\x03\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x80\x00\x00\xb0\x05\x00-v\xd3?\xa1{\x9c\xd0|\xae\xe5b\xad\xc2N\xf9aJ\xfao\xfd\x03j\xc37R\xdf\x1c2Aeg\x96&\xbd\xc2\xeaP\x12\x8d\x13\x04apBU\xd1\x97'

data part to decrypt:
data = 'v\xd3?\xa1{\x9c\xd0|\xae\xe5b\xad\xc2N\xf9aJ\xfao\xfd\x03j\xc37R\xdf\x1c2Aeg\x96&\xbd\xc2\xeaP\x12\x8d\x13\x04apBU\xd1\x97'

key='WMfc9i0Kq9cTdhgv'
but the decrypt(data,key) gave me a blank string,is this a compatibility problem,the original data is from java platform?

**Comment by ifduyue** [comment]
Hello @cnritng,

Where did you get this original data?
I haven't written any Java implementation for XXTEA until now.

**Comment by ifduyue** [comment]
Close as no response.

**Comment by cnritng** [comment]
@ifduyue Hi,sorrry for not responding in time,it's base64 data response from server,i am not quite sure about the type of the decryption key,is it in bytes or bytearray or string?
