### ISSUE TITLE
bytes count changes? C code can't decrypt

### ISSUE THREAD

**Issue by huhutm** [ifduyue/xxtea#13]
I use this lib to encrypt 16byte data,  after encrypt the data length is 20bytes.
Bute C code xxtea will not change the length. Why?

**Comment by ifduyue** [comment]
@huhutm This is because encrypted data was padded.

Though the data length changed, there would be no problem decrypting it.

**Comment by huhutm** [comment]
@ifduyue 
But After I encrypt use the lib, I can't decrypt it with another C program. The C program only decrypt 16 bytes data.

**Comment by ifduyue** [comment]
> @ifduyue
> But After I encrypt use the lib, I can't decrypt it with another C program. The C program only decrypt 16 bytes data.

Please read the readme https://github.com/ifduyue/xxtea#xxtea--

> The XXTEA algorithm takes a 128-bit key and operates on an array of 32-bit integers (at least 2 integers), but it doesn't define the conversions between bytes and array. Due to this reason, many XXTEA implementations out there are not compatible with each other.

You can only encrypt and decrypt using this python lib, as it's not compatible of any other libs.

**Comment by huhutm** [comment]
OK, thank you!
