### ISSUE TITLE
 Error installing on Windows 10 / Python 2.7.12 32 bit

### ISSUE THREAD

**Issue by cnritng** [ifduyue/xxtea#14]
Related logs are as belows:

C:\WINDOWS\system32>pip install xxtea -U
Collecting xxtea
  Using cached xxtea-1.0.2.tar.gz
Installing collected packages: xxtea
  Running setup.py install for xxtea ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\pla\appdata\local\temp\pip-build-rkwgrr\xxtea\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\pla\appdata\local\temp\pip-bm2_qm-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxtea' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DVERSION=1.0.2 -Ic:\python27\include -Ic:\python27\PC /Tcxxtea.c /Fobuild\temp.win32-2.7\Release\xxtea.obj
    xxtea.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(92) : warning C4005: '_CRT_STRINGIZE' : macro redefinition
            C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\crtdefs.h(180) : see previous definition of '_CRT_STRINGIZE'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(95) : warning C4005: '_CRT_WIDE' : macro redefinition
            C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\crtdefs.h(185) : see previous definition of '_CRT_WIDE'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(156) : warning C4005: '__CRTDECL' : macro redefinition
            C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\crtdefs.h(650) : see previous definition of '__CRTDECL'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(210) : error C2061: syntax error : identifier '__vcrt_bool'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(210) : error C2059: syntax error : ';'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(293) : warning C4005: '_CRT_WARNING' : macro redefinition
            C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\crtwrn.h(24) : see previous definition of '_CRT_WARNING'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(111) : warning C4005: 'WCHAR_MIN' : macro redefinition
            C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\wchar.h(43) : see previous definition of 'WCHAR_MIN'
    xxtea.c(70) : warning C4018: '<' : signed/unsigned mismatch
    error: command 'C:\Users\PLA\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2

```
----------------------------------------
```

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\pla\appdata\local\temp\pip-build-rkwgrr\xxtea\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\pla\appdata\local\temp\pip-bm2_qm-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\pla\appdata\local\temp\pip-build-rkwgrr\xxtea\

**Comment by ifduyue** [comment]
@cnritng Thanks for reporting this, have no Windows around now, I'll find a way to locate the problem

**Comment by ifduyue** [comment]
@cnritng Fixed in latest master
