### ISSUE TITLE
DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

### ISSUE THREAD

**Issue by pavlukivan** [ifduyue/xxtea#19]
example fix: https://github.com/python-pillow/Pillow/pull/3749/files

**Comment by pavlukivan** [comment]
more details: https://bugs.python.org/issue36381

**Comment by ifduyue** [comment]
Thanks for bringing this to my attention

**Comment by ifduyue** [comment]
I have changed `s#` to `y*`, the latter is better because we want only bytes.

**Comment by ifduyue** [comment]
Oops, python 2 has no `y*`

**Comment by ifduyue** [comment]
> Oops, python 2 has no `y*`

Fixed in b080df8

**Comment by ifduyue** [comment]
Fix is on master branch, will be included in the next release
