### ISSUE TITLE
Error when compiling on Windows / Py3

### ISSUE THREAD

**Issue by SimonSteinberger** [ifduyue/xxtea#2]
To compile xxtea on Windows / 32 bit / MSVS 10 Express, the declarations on line 165 (int i, j, top, bot;) need to be moved to the first line of the function definition. Don't know if this is a problem on other systems, as well.

**Comment by ifduyue** [comment]
Yes, declarations should go at the beginning of a function.
Would you mind sending a pull request?

**Comment by SimonSteinberger** [comment]
Ehm, don't know how - but it's just moving up one line of code. So, not a big deal :-)

**Comment by ifduyue** [comment]
@SimonSteinberger I've pushed a new version to PyPI

**Comment by SimonSteinberger** [comment]
Perfect, thanks :)
