### ISSUE TITLE
encrypt_hex should be encrypt, decrypt_hex should be decryt

### ISSUE THREAD

**Issue by SimonSteinberger** [ifduyue/xxtea#5]
With the C-based version of XXTEA, the methods "encrypt" and "decrypt" were replaced with "encrypt_hex" and "decrypt_hex", respectively. However, concerning future development, it would probably make a lot sense not to introduce new method names for the default behavior.

I'd suggest to rename the current "encrypt" into "encrypt_raw", and "encrypt_hex" back into "encrypt". The same with decrypt. This also maintains backwards compatibility and consistency concerning method names.

**Comment by ifduyue** [comment]
Yes, it's an incompatible change. But it is simpler than the previous ones. 
If we renamed `encrypt` into `encrypt_raw`, and `encrypt_hex` into `encrypt`, it's another incompatible change.
So, maybe it is easier to change the app code, how do you think?
I know this may sound unfriendly, but sorry. And I will try to maintain backwards as possible as I can from now on.

**Comment by ifduyue** [comment]
The core method of XXTEA, (btea](https://github.com/ifduyue/xxtea/blob/master/xxtea.c#L51), operates on an array of int32. After calling btea, longs2bytes is called to convert the array into binary bytes. And we need another step, hexlify, to convert binary bytes into hex representation. According to this reason, it is natural that `encrpyt` returns bytes, isn't it?

A good example to look at is [hashlib](https://docs.python.org/2/library/hashlib.html#hashlib.hash.digest), where `digest` returns bytes, and `hexdigest` returns hex.

**Comment by SimonSteinberger** [comment]
Hi ifduyue, we've already adapted our code, so that's not a problem. It was just a bit confusing and it seemed to us the other way around was more intuitive. I didn't realize hashlib was working similarly here. So, I think you're right :)
